### ISSUE TITLE
animated tracking protection icon (shield) positioned incorrectly

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#165]
Although the static shield icon is not displayed, the space for it is still reserved and pushes the animated icon down.
![ff-urlbar-shield-glitch](https://user-images.githubusercontent.com/26410884/67666291-cf861a80-f96b-11e9-96ce-b52549779d0b.png)
Reproduction link: https://www.minecraft.net/en-us/
OS: Win10
FF Version: 70

**Comment by muckSponge** [comment]
Can't reproduce on my end. Are there specific tracking settings I need to be using?

**Comment by bucklingspring** [comment]
@muckSponge I've encountered this too. 
![image](https://user-images.githubusercontent.com/32025806/68081012-13da4600-fdc4-11e9-98d8-e12ef9638ebd.png)

It happens when using a page with content that Firefox blocks based on your tracking protection settings, as indicated by the coloured shield icon in the address bar.

![image](https://user-images.githubusercontent.com/32025806/68081022-471cd500-fdc4-11e9-9b69-40df59ed58c2.png)
![image](https://user-images.githubusercontent.com/32025806/68081024-5ac83b80-fdc4-11e9-9f6e-78386b666bf0.png)

**Comment by 0x3b0c** [comment]
the shield icon height has been changed from 20px to 16px, the tracking-protection-icon-animatable-box element is positioning the animated svg using top: calc(50% - 10px), changed to top: calc(50% - 8px) and it solves the issue on my installation, anyone can check this?


Code added to urlbar.css:

```
#tracking-protection-icon-box > #tracking-protection-icon-animatable-box {
    top: calc(50% - 8px) !important; /* half the height of the sprite */
	height: 16px !important;
}
```

**Comment by leogx9r** [comment]
@0x3b0c Yes, works fine on my end.

**Comment by fmeyertoens** [comment]
It works indeed. Where did you find: `top: calc(50% - 10px)`? I couldn't see that anywhere?
This whole issue doesn't affect FF 71 btw so we should check that any fix we apply now has no negative effects then.

**Comment by 0x3b0c** [comment]
@fmeyertoens from here:
https://hg.mozilla.org/mozilla-central/file/540f0f87e031860704af22b22e1aaecac2d27064/browser/themes/shared/identity-block/identity-block.inc.css

**Comment by fmeyertoens** [comment]
Ok I see, but the idea is right. They recently changed it.
https://hg.mozilla.org/mozilla-central/file/tip/browser/themes/shared/identity-block/identity-block.inc.css#l260
```css
#tracking-protection-icon-box:not([hasException])[active] #tracking-protection-icon-animatable-image {
  /* Overrides the default 'display: -moz-box' to prevent icon shifting issue
     with scaled text, see Bug 1591049 */
  display: block;
  background-image: url(chrome://browser/skin/tracking-protection-animation.svg);
...
  height: 16px;
...
}
```
