### ISSUE TITLE
Make the context menu smaller

### ISSUE THREAD

**Issue by Diyamund** [muckSponge/MaterialFox#275]
The context menu looks way too tall to be used on a desktop PC. You should definitely make it less tall.

**Comment by NICHOLAS85** [comment]
I use the following to make the context menu smaller, you could probably adjust it to your liking:
```css
/* Smaller context popup */
menupopup menuitem,
menupopup menu,
.autocomplete-richlistitem
{
	height: inherit !important;
	padding: 4px 16px !important;
	border: 0 !important;
	background: 0 !important;
	color: inherit !important;
	fill-opacity: initial !important;
}
```
