### ISSUE TITLE
Chromium-style page info

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#49]
I think the page info popup can also be made quite similar to Chromium's. Here's my (working, but not  pretty yet) start on it, feel free to include:
<details><summary>Code inside</summary>

```css
#identity-popup-mainView { /* Limit overall popup width - default is 33 */
    min-width: 25em !important;
    max-width: 25em !important;
}

#identity-popup-mainView-panel-header { /* Remove primary header "Site information for..." */
  display: none !important;
}

.identity-popup-security-content > description { 
  font-size: 135% !important; /* Increase security text size */
  -moz-box-ordinal-group: 0 !important; /* Make the text topmost */
}

.identity-popup-headline {
  font-size: 100% !important; !important; /* Decrease domain font size to look like the 3 bottom-aligned buttons on Chromium */
  margin-block-start: 0.4em !important; /* Add space between the domain and security state */
  margin-inline-start: 0.2em !important; /* Align similarly to permissions */
}

#identity-popup-security-descriptions > description {
  color: inherit !important; /* Black text for security description */
  font-size: 100% !important; /* Normalize description text */
}

.identity-popup-warning-gray, .identity-popup-warning-yellow {
  background: none !important; /* Remove in-text triangles for mixed content */
  padding-inline-start: 0em !important;
}

#tracking-protection-label, #content-blocking-label, #identity-popup-permissions-headline {
  font-size: 100% !important; !important; /* Decrease category title font size to look like the 3 bottom-aligned buttons on Chromium */
  margin-inline-start: 0.6em !important; /* Align similarly to permissions */
  margin-block-end: 0em !important; /* Remove bottom margin */
}

.identity-popup-security-content, #identity-popup-permissions-content, #identity-popup-content-blocking-content {
  background-image: none !important; /* Remove big category icons */
  padding: 0.5em !important; /* Normalize padding */
}

/* Hide generic messages, including: */
#identity-popup-content-blocking-not-detected, /* Blockable content not detected */
#identity-popup-content-blocking-detected, /* Blockable content detected */
#identity-popup-content-blocking-disabled-label, /* Content blocking itself disabled */
#identity-popup-permission-empty-hint { /* Permissions not given */
  display: none !important;
}

.identity-popup-section {
    border-top: none !important; /* Remove separators */
}

#identity-popup-security-expander {
   /* The inline identity info button - could look like the Certificate button on Chromium */
  
  -moz-box-ordinal-group: 0 !important; /* Move the expanding arrow before text */
  background: none !important;
  
  /* Demo: low-res cert icon */
  list-style-image:  url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4goOETk3luqeSQAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAExSURBVCjPlZK9TsJgFIYfoSOd6IIjJi2jTBK8BaUmYHDBRePNEK9A0URWYQAmDG6WO4D2Gy0LTbsUUyesg2lj/eHnnc75zvuck7z5duZzJ3xot1kuP9hE6XSK80YDqdPtMp2abKPHTgfJ9xcAqKpKQVNXAqYlEEKwWLwhRY+KkkUraCtB1/MQ4quOQcuycF0vYRSR6w/F4GG5jK5XEsOLy6v1YK8/oNcfbBxQDFaOj9D1CqZl0Wxex4ZicZ+zeh3Hcbi5beH7fhJ8MQxMS/AeBInNJ7qOomRRlCyl0gHD4RMAqcigaRp7+Tz2bJYAbdsGIAxDZt9m8UXX9Qh+XANo3d2T281hGGMmk+lv8L/owzBkNHrGfrWT4chyZm2ChjFO9LKcQTqtVQmCYKtPXqtW+QRoEHiPUN97ZgAAAABJRU5ErkJggg==') !important;
}

.identity-popup-expander > .button-box {
  -moz-box-ordinal-group: 99 !important;
  border-right: none !important; /* Remove inline identity separator */
}

#identity-popup-securityView-body {
  margin-inline-start: 1em !important; /* Fix security details padding when opened */
} 

.identity-popup-preferences-button {
  /* The Content Blocking settings button - could look a fill-width button on Chromium, but with adblock icon */
  
   -moz-box-ordinal-group: 0 !important; /* Move settings buttons before text to look more like Chromium full-width buttons*/
  
  /* Demo: low-res adblock icon */
   list-style-image:  url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAOCAYAAAAmL5yKAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4goOEToUH6C8+AAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAACiSURBVCjPY/z9+/f/7Tt2M1y7foPh////DMQARkZGBi1NDQZPD1cGliNHjzOs27CJgVRw4+YtBl5eHgamDx8+MpALPnz4yMAC4ygqyDOwsbERpfHXr18M9x88ZGBgYEAYkJIUzyAlJUmUAU+fPWOoqWtmYGBgYGBioBCMGjAYDGAREOBnYGBgYKiuayJZs4AAPwOLjbUlw+fPX8jKTDbWlgwAZgMxfMlgM2AAAAAASUVORK5CYII=') !important; */
}

#identity-popup-clear-sitedata-button {
  /* "Clear Cookies and Site Data..." button - make it look like the cookie button */
  
  background: white !important;
  border-block-start: none !important;
  
  margin-left: -8em !important; /* Hacky way to left-align the button, there are probably better ways */
  
  /* Demo: low-res cookie icon */
  list-style-image:  url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4goOETsMFdcV7wAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAJFSURBVDjLjZNLT1NhEIaf0sppm5LQixIESxqhiJKuhAh4gY0QNYIRUIGfIJioe6Mb0agxQoyiiGsvJCBuMAi6EBRRYGELKSkWVi1NBQsnQDmfi6OFWjDObpKZ531nMqMRQgj+CkVR8HqnmJmdZbvNisvlYqvQbUzm5ubo7X3Dx0/DRCIRAPbk5v4fwOfzcfvOXWRZjitYU9b4VyQBRCIR7rW0IssyKSkpXGg6T+mRwwBMT3/nxs1bjI2Nb+3g2fMXLCz8BCAzMxOXy4Veb2Dg3XtWV1eZnJwkOXkbkl4ibUcaZnNqDKCZn18QFy9dZuMu7XY7oVCIxcXFBMWMjAyuXb2y7sDj8SCEoLLyJDvT02l79Bi/37/lzMFgkK6ubpK0Wg4dLEEXDocBKCkuxmq18LKzk0AgiMlk4uyZWr6OjjIy8iUGWFlZoftVj5oIgS66pm75enMzkqQnEAgCUFhYQFHRAYxGYwyQlWXH75+JjStJEjqrxQJAOPwjzurg4BBGo5HxcXX7NdWnqagop739CR8GhwCw2WzonM6cTWeVZZmentdx1hVFYWlJvRONRkN+/j40Qgjx4GEbw8Of4wAOhwOnM4e+vrdEo9EEgbKyUhrq69RDaqivw2QyxRU01J+jtqaavXl5Cc0Wi4VTVVWqkz/P5Ha7aWm9z/LyMgDZ2btxOBz09w/EOTCbU2lqbMRu3xUPUJ8pREfHUzwTEwmqWq2WE8ePUV5+FEmS1i9xs3f2eqf45nYjFOW3qpmCgv0YDIYE8C/lYedSnVP+RQAAAABJRU5ErkJggg==') !important;
}

#identity-popup-permission-preferences-button {
  /* The permission settings button - could look like Site Settings on Chromium */
  
  /* Demo: low-res cog (page settings) icon */
  list-style-image:  url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4goOEToxVKRovwAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAAHqSURBVDjLlZNNU1JhFMd/h3sdWFzABSPBAoYPkEsvUE4Bu+wFnElzX32IUkvBPkS1rzaiM+rOcgc4Ywv7ANfbDDCYCxjc2eVpQVxRpJnO6rz+n/Oc/zmilFLcIPv7Xzk/PwfAMAxyuexNaeiMkU+fvzDAFpGxAJ6B0mq1cBwHgBPbZrgxpRQntg2A4zi0Wi03Jkop1e50eP1qGX1igunp21QqVa7/TERIpZIcH//g98UFG+9KTAaDfYD3Hz5Sqx3yP2KaM7x88RxPs9m8sXhqaorHjx4ye/cOPp9vJF6rHdJoNJBer6fKW9vs7u65wUAgwPraG/x+PwDtTodicYN2u+3mzM09oJB/gkdEmC/kSZqmG8xlM24xwGQwSDZz37XTqSTzhTwicsmCeMRN0HRtpOXe0FCHdY9Sis3NMpVK1XUeHX2/wkK32+Xg24FrV6s1ylvbKKWQer2uVlbfjryYSCTIZO4BsLOzx+np6UhOqbiGHo1GMc2ZESYsy8KyrLE0Jk2TSCTSn8HCwlN8Xi+GYZBOpxCRkQIRIZ1OYRgGPq+XpaXFy00crHIoFELTNGz7J+vF0hWA1ZVl4vEYjuPw6+yMW+Hw1WMK/3UAxOMxRMQdpK7rxOOxPkOa5hb/8xqXni1envPQTlyXP5pov06hpTmBAAAAAElFTkSuQmCC') !important;
}

.identity-popup-permission-item, /* Permission item */
#identity-popup-content-blocking-category-fastblock, /* Slow-loading trackers */
#identity-popup-content-blocking-category-tracking-protection, /* All detected trackers */
#identity-popup-content-blocking-category-3rdpartycookies { /* Third-party cookies */
 margin: 0.5em !important; /* More margin for Chrome likeness */
}

.identity-popup-content-blocking-category, .identity-popup-permission-item {
  padding-inline-start: 2.2em !important; /* Add padding to content blocking/permission items in order to make their icons visible */
}

.desktop-notification-icon {
  /* Demo: low-res notification icon */
  list-style-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAPCAYAAADQ4S5JAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAB3RJTUUH4goOETsiyQEYIAAAABl0RVh0Q29tbWVudABDcmVhdGVkIHdpdGggR0lNUFeBDhcAAADhSURBVCjPlZJNboJAGECf1A0XqSegS3uRxgtUV9p26x3Uhel1DDWCWwnQJS4d0JowC9LPjWCdGglvN/nem59kEIOiKOTt/UOGw5Forc2xWBh8LZfsdoo02+P5vjmmJSICkOc5k+mMMIyuhE7nkUH/Fdu2AahOuCUDhGHEZDqr1hZAHH/flP9GURxfgiRJqGObbC/BYX+oDUrHAji/+y6lY9GQ5oFSGQvXrRUXrotSGQ+/wjhN09pAa8167dPaBIE0uVL1NUpWnsd8/glAr/fCc7d7FbTNHZ4ch+PPEeCfDHACeoiOLJ50LOEAAAAASUVORK5CYII=') !important;
}
```
</details>
<br>

Edit 07.10: improved design
Edit 14.10: added demo icons
Edit 12.11: fixes for FX 64
