### ISSUE TITLE
Chrome-like search results

### ISSUE THREAD

**Issue by RisingFireStar** [muckSponge/MaterialFox#50]
Any plans for trying to make chrome-like search results?
![search results](https://user-images.githubusercontent.com/23248936/46574329-278d6000-c9aa-11e8-9057-33e4c58f67b2.png)

**Comment by Madis0** [comment]
You should clarify that you mean the _autocomplete_ search results.

**Comment by muckSponge** [comment]
Unfortunately the autocomplete search results are not nested in the urlbar so they can't inherit its width but we should be able to do something about the overall style.

**Comment by sagudev** [comment]
What about if we made Firefox based browser that act like Chrome (UI and autocomplete for now)

**Comment by muckSponge** [comment]
> What about if we made Firefox based browser that act like Chrome (UI and autocomplete for now)

I think that's a bit outside of the scope of this project. You have to consider whether something that involved is actually worth the outcome. I think it's a better idea to style it in a similar fashion to Chrome where possible, but where it can't be helped with a userChrome theme, do it the Firefox way.

A specific fork of Firefox for this theme would further restrict the target audience.

**Comment by Eddi2015** [comment]
Yeah IMO keeping up with the latest firefox builds and patches would be too much work, so better we keep it like that. My idea would be to make some sort of platform independet (maybe written in Java?) installer with gui for the 'noobs'. In this installer you can also decide whter to include the different about:config tweaks or not. Maybe I'm going to try to write such an installer. We'll see.

**Comment by Madis0** [comment]
@Eddi2015 You may be interested in this: https://github.com/NiklasGollenstede/re-style/issues/21.

For context: [reStyle](https://addons.mozilla.org/en-US/firefox/addon/re-style/) is a Firefox extension for installing and managing userStyles, even the GUI ones on Firefox 57+. You may think of it as a feature Stylish used to have.

Though, the problem with this style specifically would be its scope (a big theme consisting of many files) so while possible, would probably prove to be quite difficult to make auto-updatable.

**Comment by sagudev** [comment]
I think we should easily change Firefox installer to install Material-Fox and all configs.

**Comment by Eddi2015** [comment]
@Madis0 I thought about some sort of external installer, not as an extension.
@sagudev This also raises the problem about staying up-to-date with the official Firefox installer. I'd rather keep such an installer seperate.

**Comment by sagudev** [comment]
@Eddi2015 With Firefox installer I mean [Firefox **stub** installer](https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/StubInstaller.html), which downloads latest Firefox version. In stub installer we just need to add script to download latest Material-Fox and then extract it to Firefox profile folder and change configs that we need.

**Comment by GenkunAbe** [comment]
I have made some preliminary modifications, and the current implementation is as follows:
![my implementation](https://user-images.githubusercontent.com/11963004/51433891-62cd4980-1c90-11e9-8fdb-5934232bc18b.gif)

The biggest problem now is that urlbar changes its style before keystrokes, rather than that in chrome:
![chrome](https://user-images.githubusercontent.com/11963004/51433917-e129eb80-1c90-11e9-9d1a-aacdf8cf618a.gif)

My CSS code of urlbar is as follows:
```CSS
#urlbar[focused="true"],
#searchbar[focused="true"]
{
    height: 36px !important;
    background-color: var(--toolbar-field-focus-background-color) !important;
    border: 0px !important;
    border-radius: 10px 10px 0 0 !important;
    box-shadow: rgba(0, 0, 0, 0.16) 2px 4px 6px 0px, rgba(0, 0, 0, 0.16) -2px 4px 6px 0px !important;
}
```

Obviously `[focused="true"]` shouldn't be used here, but I don't know what element selector to use.

**Comment by muckSponge** [comment]
@GenkunAbe, how are you setting the urlbar results width? Mine always occupies the full width of the window.

**Comment by GenkunAbe** [comment]
I noticed that although the resulting list is full width, the texts and urls inside are always aligned with the urlbar. 

After inspecting the text elements, two variables were found to control the left and right padding: `--item-padding-end` and `--item-padding-start`, so my CSS code is:

```CSS
#PopupAutoCompleteRichResult .autocomplete-richlistbox {
    margin: 0px var(--item-padding-end) 16px calc(var(--item-padding-start) + 22px) !important;
}
```
