### ISSUE TITLE
Actions UI on macOS Mojave

### ISSUE THREAD

**Issue by ronilaukkarinen** [muckSponge/MaterialFox#53]
Hello! I just noticed on macOS the close, maximize and minimize icons are not centered like in the screenshots. Bothers me a bit.

![Screenshot](https://i.imgur.com/ueSiZ9r.png)

**Comment by ronilaukkarinen** [comment]
Used the browser toolbox to align them by adding this to the end of the global.css:

```` css
#titlebar-buttonbox {
	margin-top: -4px !important;
	margin-left: 10px !important;
}
````

I would have done a PR, but not sure if this messes up the buttons on Windows/Linux version... gotta test soon on Windows computer, will do a PR then.
