### ISSUE TITLE
Bookmark Menu

### ISSUE THREAD

**Issue by stevebaines** [muckSponge/MaterialFox#86]
Hi,  I've removed the favicons from the bookmark bar with 
```
.bookmark-item .toolbarbutton-icon 
{display:none !important;}
```
Is there a way to increase the width of circle.svg without just increasing padding.  I'm happy with the height?  I ralise that you probably don't have time to help people who are just mucking about with your code, but I thought I'd ask. Many thanks.

**Comment by muckSponge** [comment]
Sorry it took me so long to get to this. circle.svg is used as a background-image (I think, it's been a while since I've touched that code). It expands to fill the container it is in as a touch ripple effect, meaning it's only visible when you click. If you'd like to increase the width of `.bookmark-item`s, you'll need to either set an explicit width:

```css
.bookmark-item
{
    width: 200px !important;
}
```

...or increase the left/right padding (this won't change the height):

```css
.bookmark-item
{
    padding-inline-start: 16px !important;
    padding-inline-end: 16px !important;
}
```
