### ISSUE TITLE
Tab flashes when switching tabs

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#99]
When switching between tabs the old tab briefly flashes in dark mode (turns black in light mode).
This happens since fea4fba9cf9e6fc4e7b8d736e5fc8fa95980acf1 probably due to:
```css
#TabsToolbar[brighttext] .tabbrowser-tab
{
    --tab-bgcolor: #fff;
}
```
and
```css
.tab-background
{
	transition: opacity .2s var(--ease-basic) !important;
	opacity: var(--tab-opacity) !important;
}
```
which produces the flash (transition).

For light mode it is 
```css
.tabbrowser-tab
{
	--tab-opacity: 0;
	--tab-bgcolor: #000;
}
```
